@startuml
'https://plantuml.com/class-diagram

class Personnage {
    - String m_nom;
    - Race m_race;
    - Classe m_classe;
    - ArrayList<Caracteristique> caracteristiques = new ArrayList<>();
    - ArrayList<Objet> m_inventaire = new ArrayList<>();
    - ArrayList<Objet> m_equipement = new ArrayList<>();
    + Personnage(string nom, Race race, Classe classe)
}

interface Caracteristique {
  + int getCaracteristique()
  + void diminuerCaracteristique(int diminution)
  + void augmenterCaracteristique(int augmentation)
}

class BaseCaracteristique {
  - int m_caracteristique
  # BaseCaracteristique(int caracteristique)
  + int getCaracteristique()
  + void diminuerCaracteristique(int diminution)
  + void augmenterCaracteristique(int augmentation)
}

class PointDeVie {
+ PointDeVie(int caracteristique)
}
class Force {
+ Force(int caracteristique)
}
class Dexterite {
+ Dexterite(int caracteristique)
}
class Vitesse {
+ Vitesse(int caracteristique)
}
class Initiative {
+ Initiative(int caracteristique)
}

PointDeVie --|> BaseCaracteristique
Force --|> BaseCaracteristique
Dexterite --|> BaseCaracteristique
Vitesse --|> BaseCaracteristique
Initiative --|> BaseCaracteristique

PointDeVie ..|> Caracteristique
Force ..|> Caracteristique
Dexterite ..|> Caracteristique
Vitesse ..|> Caracteristique
Initiative ..|> Caracteristique

BaseCaracteristique ..|> Caracteristique

interface Objet {
  + String getNom()
}

class Armure {
- String m_nom;
- int m_classe;
# Armure(String nom, int classe)
+ int getClasse()
}

class Arme {
- String m_nom;
- int m_porte;
# Arme(String nom, int porte)
+ int getPorte()
}

Armure ..|> Objet
Arme ..|> Objet

class ArmureLegere {
+ ArmureLegere(String nom, int classe)
}
class ArmureLourde {
+ ArmureLourde(String nom, int classe)
}
class ArmeCourante {
+ ArmeCourante(String nom, int classe)
}
class ArmeGuerre {
+ ArmeGuerre(String nom, int classe)
}
class ArmeDistance {
+ ArmeDistance(String nom, int classe)
}

ArmureLegere --|> Armure
ArmureLegere ..|> Objet
ArmureLourde --|> Armure
ArmureLourde ..|> Objet
ArmeCourante --|> Arme
ArmeCourante ..|> Objet
ArmeGuerre --|> Arme
ArmeGuerre ..|> Objet
ArmeDistance --|> Arme
ArmeDistance ..|> Objet

interface Classe {
  + int getPointDeVie()
}

class Clerc
class Guerrier
class Magicien
class Roublard

BaseClasse ..|> Classe

Clerc --|> BaseClasse
Clerc ..|> Classe

Guerrier --|> BaseClasse
Guerrier ..|> Classe

Magicien --|> BaseClasse
Magicien ..|> Classe

Roublard --|> BaseClasse
Roublard ..|> Classe


@enduml