@startuml
left to right direction

class Main {

}

package Entites {
    package Personnages {
        class Personnage {
            - String m_nom
            - Race m_race
            - Classe m_classe
            - Caracteristique caracteristiques
            - ArrayList<Objet> m_inventaire
            - ArrayList<Objet> m_equipement
            +«Create» Personnage(string nom, Race race, Classe classe)
        }
    }

    class MaitreJeu {
        - Donjon donjonParDefault
    }

    package Races {
        abstract Race {
            +«Create» Race(s
        }

        class Elfe {

        }

        class Halfelin {

        }

        class Humain {

        }

        class Nain {

        }

        Elfe --> Race
        Halfelin --> Race
        Humain --> Race
        Nain --> Race
    }

    Personnage "Utilise" -down.> Race

    package Classes {
        abstract Classe {
            - int pv
            + int getPointDeVie()
            + int getEquipement()
        }

        class Clerc {
            +«Create» Clerc(String nom, int pdv)
        }
        class Guerrier {
            +«Create» Guerrier(String nom, int pdv)
        }
        class Magicien {
            +«Create» Magicien(String nom, int pdv)
        }
        class Roublard {
            +«Create» Roublard(String nom, int pdv)
        }

        Clerc --|> Classe

        Guerrier --|> Classe

        Magicien --|> Classe

        Roublard --|> Classe
    }

    Personnage "Utilise" -down.> Classe

    package Monstres {
        class Monstre {
            - String m_espece
            - int m_numero
            - Attaque m_attaque
            - ArrayList<Caracteristique> m_caracteristiques
            +«Create» Monstre(String espece, int numero, <Attaque> attaque, ArrayList<Caracteristique> caracteristiques)
        }
    }

    package Caracteristiques {
        class Caracteristique {
            - m_pv : int
            - m_force : int
            - m_dexterite : int
            - m_vitesse : int
            - m_initiative : int

            +«Create» Caracteristique(pv: int, force: int, dexterite: int, vitesse: int, initiative: int)
            + getPv() : int
            + getForce() : int
            + getDexterite() : int
            + getVitesse() : int
            + getInitiative() : int
            + changerPv(changement: int) : void
            + changerForce(changement: int) : void
            + changerDexterite(changement: int) : void
            + changerVitesse(changement: int) : void
            + changerInitiative(changement: int) : void
        }

        class CaracteristiqueMonstre {
            - m_classeArmure : int
            +«Create» CaracteristiqueMonstre(pv: int, force: int, dexterite: int, vitesse: int, initiative: int, classeArmure:int)
            + getClasseArmure() : int
            + changerClasseArmure(changement: int) : void
        }

        Caracteristique -left--> CaracteristiqueMonstre
    }

    Monstre "Utilise" -down.> CaracteristiqueMonstre
    Personnage "Utilise" -down.> Caracteristique
}

package Objets {
    interface Objet {
      + String getNom()
    }

    package Armes {
        class Arme {
            - String m_nom;
            - int m_porte;
            +«Create» Arme(String nom, int porte)
            + int getPorte()
        }
        Arme ..|> Objet

        class ArmeGuerre {
        +«Create» ArmeGuerre(String nom, int classe)
        }
        class ArmeDistance {
        +«Create» ArmeDistance(String nom, int classe)
        }
        class ArmeCourante {
        +«Create» ArmeCourante(String nom, int classe)
        }

        ArmeCourante --|> Arme
        ArmeCourante ..|> Objet
        ArmeGuerre --|> Arme
        ArmeGuerre ..|> Objet
        ArmeDistance --|> Arme
        ArmeDistance ..|> Objet
    }
    package Armures {
        class Armure {
            - String m_nom;
            - int m_classe;
            +«Create» Armure(String nom, int classe)
            + int getClasse()
        }
        Armure ..|> Objet

        class ArmureLegere {
            +«Create» ArmureLegere(String nom, int classe)
        }
        class ArmureLourde {
            +«Create» ArmureLourde(String nom, int classe)
        }

        ArmureLegere --|> Armure
        ArmureLegere ..|> Objet
        ArmureLourde --|> Armure
        ArmureLourde ..|> Objet
    }
}

Personnage "Utilise" -down.> Objet

package Donjons {
    class Donjon {
        - int[2] m_dimensions
        - int[][] m_cases
        - String contexte
        +«Create» Donjon(int x, int y)
    }
}

package Des {
    class De {
        + {static} int lancer(int nbDes, int nbFaces)
    }
}

@enduml